/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as OscilloscopeRouteImport } from './routes/oscilloscope'
import { Route as MouseRouteImport } from './routes/mouse'
import { Route as ColorRouteImport } from './routes/color'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const OscilloscopeRoute = OscilloscopeRouteImport.update({
  id: '/oscilloscope',
  path: '/oscilloscope',
  getParentRoute: () => rootRouteImport,
} as any)
const MouseRoute = MouseRouteImport.update({
  id: '/mouse',
  path: '/mouse',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorRoute = ColorRouteImport.update({
  id: '/color',
  path: '/color',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/color': typeof ColorRoute
  '/mouse': typeof MouseRoute
  '/oscilloscope': typeof OscilloscopeRoute
  '/terminal': typeof TerminalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/color': typeof ColorRoute
  '/mouse': typeof MouseRoute
  '/oscilloscope': typeof OscilloscopeRoute
  '/terminal': typeof TerminalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/color': typeof ColorRoute
  '/mouse': typeof MouseRoute
  '/oscilloscope': typeof OscilloscopeRoute
  '/terminal': typeof TerminalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/color'
    | '/mouse'
    | '/oscilloscope'
    | '/terminal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/color'
    | '/mouse'
    | '/oscilloscope'
    | '/terminal'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/color'
    | '/mouse'
    | '/oscilloscope'
    | '/terminal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ColorRoute: typeof ColorRoute
  MouseRoute: typeof MouseRoute
  OscilloscopeRoute: typeof OscilloscopeRoute
  TerminalRoute: typeof TerminalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oscilloscope': {
      id: '/oscilloscope'
      path: '/oscilloscope'
      fullPath: '/oscilloscope'
      preLoaderRoute: typeof OscilloscopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mouse': {
      id: '/mouse'
      path: '/mouse'
      fullPath: '/mouse'
      preLoaderRoute: typeof MouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color': {
      id: '/color'
      path: '/color'
      fullPath: '/color'
      preLoaderRoute: typeof ColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ColorRoute: ColorRoute,
  MouseRoute: MouseRoute,
  OscilloscopeRoute: OscilloscopeRoute,
  TerminalRoute: TerminalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
